require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

# https://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod
# https://github.com/facebook/react-native/issues/28503
# deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.
# reactnative module map file not found
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      #config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

target 'AgoraLivestreamingApp' do
  #config = use_native_modules!

  #use_react_native!(:path => config["reactNativePath"])

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'AgoraLivestreamingAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'AgoraLivestreamingApp-tvOS' do
  # Pods for AgoraLivestreamingApp-tvOS

  target 'AgoraLivestreamingApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
